name: Setup Java & Mill Cache

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Cache Mill & Coursier directories
      uses: actions/cache@v4
      with:
        path: |
          ~/.mill
          ~/.coursier
          ~/.cache/mill
          ~/.cache/coursier
          ~/.cache/cs
        key: ${{ runner.os }}-mill-${{ hashFiles('build.mill') }}
        restore-keys: |
          ${{ runner.os }}-mill-
    
    # All the Mill jobs require the local build of Kyo, through the Ivy2 local repository.
    # So we download it here to avoid duplicating this step in all Mill jobs.
    - uses: actions/download-artifact@v5
      with:
        name: ivy2-local
        path: ~/.ivy2/local