name: Setup repo, Java, caches & Mill

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Cache Mill, Ivy & Coursier
      uses: actions/cache@v4
      with:
        path: |
          ~/.mill
          ~/.ivy2/cache
          !~/.ivy2/cache/**/ivydata-*.properties
          ~/.ivy2/local
          ~/.sbt
          ~/.cache/coursier
        key: ${{ runner.os }}-mill-${{ hashFiles('build.mill') }}
        restore-keys: |
          ${{ runner.os }}-mill-
    
    - name: Cache Mill build outputs (out/)
      uses: actions/cache@v4
      with:
        path: out
        key: ${{ runner.os }}-mill-${{ github.run_id }}
