name: CI (Testing & Packaging)

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mill-setup

      # ---- Kyo ----
      - name: Cache sbt & kyo
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            kyo-src/out
          key: ${{ runner.os }}-kyo

      - uses: sbt/setup-sbt@v1
      
      - name: Grab source
        run: git clone --depth 1 --branch main https://github.com/Iltotore/kyo.git kyo-src
      
      - name: Install
        run: |
          cd kyo-src
          sbt publishLocal
          cd ..
      
      # ---- Back to Mill ----
      - name: Prepare Mill
        run: ./millw -i __.compile

  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mill-setup

      - name: Setup Mill, install dependencies & run tests
        run: ./millw test

  package:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mill-setup

      - name: Setup Mill, install dependencies & run packaging
        run: ./millw assembly
      
      - uses: tj-actions/branch-names@v9
        id: branch-name

      - name: Format branch name
        id: format-branch-name
        run: echo "formatted_branch=$(echo ${{ steps.branch-name.outputs.current_branch }} | tr -s '/' '-')" >> $GITHUB_OUTPUT
      
      - uses: actions/upload-artifact@v4
        with:
          name: algorab-artifacts-${{ steps.format-branch-name.outputs.formatted_branch }}
          path: 'out/assembly.dest/*.jar'