name: CI (Testing & Packaging)

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup repo, Java, caches & Mill
        uses: ./.github/actions/mill-setup
      
      # ------ Kyo Workaround ------

      # I actually miss Python and Rust here allowing direct compilation of dependencies via source.
      # - JordanViknar

      - name: KYO - Setup SBT
        uses: sbt/setup-sbt@v1
      
      - name: KYO - Grab source
        run: git clone --depth 1 --branch main https://github.com/Iltotore/kyo.git kyo-src
      
      - name: KYO - Install
        run: |
          cd kyo-src
          sbt publishLocal
          cd ..
          rm -rf kyo-src
      
      # ------ End Kyo Workaround ------
      
      - name: Prepare Mill
        run: ./millw -i __.compile

  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup repo, Java, caches & Mill
        uses: ./.github/actions/mill-setup

      - name: Setup Mill, install dependencies & run tests
        run: ./millw test

  package:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup repo, Java, caches & Mill
        uses: ./.github/actions/mill-setup

      - name: Setup Mill, install dependencies & run packaging
        run: ./millw assembly
      
      - name: Extract current branch name
        id: branch-name
        uses: tj-actions/branch-names@v9

      - name: Format branch name
        id: format-branch-name
        run: echo "formatted_branch=$(echo ${{ steps.branch-name.outputs.current_branch }} | tr -s '/' '-')" >> $GITHUB_OUTPUT
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: algorab-artifacts-${{ steps.format-branch-name.outputs.formatted_branch }}
          path: 'out/assembly.dest/*.jar'